name: Create VSIX

on: push

jobs:
  Build-VSIX:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm install 
          npm install -g vsce 
          npm install webpack

      - name: Build VSIX
        run: |
          npm run enableWebpack
          vsce package
        
      - name: Read version in package.json
        id: read-version
        run: |
          echo "version=$(npm pkg get version | tr -d '"')" >> $GITHUB_OUTPUT

      - name: Upload VSIX
        uses: actions/upload-artifact@v3
        with:
          path: vdm-vscode-${{ steps.read-version.outputs.version }}.vsix
          name: vdm-vscode-${{ steps.read-version.outputs.version }}.vsix
          
      - name: Update release if release branch
        if: ${{ startsWith(github.ref_name, 'release-') }}
        run: |
          TAG=$(echo $BRANCH | sed -e "s/^release-//")
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git tag -f $TAG
          git push --force origin $TAG
          gh release upload $TAG vdm-vscode-${{ steps.read-version.outputs.version }}.vsix --clobber
        env:
          BRANCH: ${{ github.ref_name }}
          GH_TOKEN: ${{ github.token }}
