name: Jar Updater

on:
  workflow_dispatch:
        
  repository_dispatch:
    types: [new-jar]

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 16
      
    - name: Log Info
      run: echo "Repository $REPOSITORY, Version $VERSION, GroupId $GROUPID, ArtifactId $ARTIFACTID"
      env:
        REPOSITORY: ${{ github.event.client_payload.repository }}
        VERSION: ${{ github.event.client_payload.version }}
        GROUPID: ${{ github.event.client_payload.groupId }}
        ARTIFACTID: ${{ github.event.client_payload.artifactId }}

    - name: Run new-jar.js
      run: node new-jar.js repo=$REPOSITORY groupId=$GROUPID artifactId=$ARTIFACTID version=$VERSION
      working-directory: resources/jars
      env:
        REPOSITORY: ${{ github.event.client_payload.repository }}
        VERSION: ${{ github.event.client_payload.version }}
        GROUPID: ${{ github.event.client_payload.groupId }}
        ARTIFACTID: ${{ github.event.client_payload.artifactId }}