name: Jar Updater

on:
  workflow_dispatch:
        
  repository_dispatch:
    types: [new-jar]

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - name: Send greeting
      run: echo "Hello ${{ github.actor }}"
