name: Manual workflow

on:
  workflow_dispatch:
        
  repository_dispatch:
    types: [test]

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - name: Send greeting
      run: echo "Hello ${{ github.actor }}"
