name: Jar Updater

on:
  workflow_dispatch:
        
  repository_dispatch:
    types: [new-jar]

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 18
        
    - name: npm install
      run: npm install
      
    - name: Log Info
      run: echo "ConfigId $CONFIGID Repository $REPOSITORY, Version $VERSION, GroupId $GROUPID, ArtifactId $ARTIFACTID"
      env:
        CONFIGID: ${{ github.event.client_payload.configId }}
        REPOSITORY: ${{ github.event.client_payload.repository }}
        VERSION: ${{ github.event.client_payload.version }}
        GROUPID: ${{ github.event.client_payload.groupId }}
        ARTIFACTID: ${{ github.event.client_payload.artifactId }}

    #- name: Run new-jar.js
    # run: node new-jar.js repo=$REPOSITORY groupId=$GROUPID artifactId=$ARTIFACTID version=$VERSION
    #  working-directory: resources/jars
    #  env:
    #    REPOSITORY: ${{ github.event.client_payload.repository }}
    #    VERSION: ${{ github.event.client_payload.version }}
    #    GROUPID: ${{ github.event.client_payload.groupId }}
    #    ARTIFACTID: ${{ github.event.client_payload.artifactId }}
    #    GITHUB_TOKEN: ${{ github.token }}

    - name: Run new-jar2.js
      run: node new-jar2.js configId=$CONFIGID version=$VERSION
      working-directory: resources/jars
      env:
        VERSION: ${{ github.event.client_payload.version }}
        CONFIGID: ${{ github.event.client_payload.configId }}

    - name: Git Status
      run: git status
