name: Jar Updater

on:
  workflow_dispatch:
        
  repository_dispatch:
    types: [new-jar]

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - name: Send greeting
      run: echo "Hello ${{ github.actor }}"
      
    - name: Repository
      run: echo "Repository $REPOSITORY, Version $VERSION"
      env:
        REPOSITORY: ${{ github.event.client_payload.repository }}
        VERSION: ${{ github.event.client_payload.version }}
